#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
#       cherrytree
#
#       Copyright 2009-2012 Giuseppe Penone <giuspen@gmail.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

import os, sys, __builtin__

if os.path.isfile('glade/cherrytree.glade'):
    SHARE_PATH = ""
    MODULES_PATH = 'modules'
else:
    if sys.platform[0:3] == "win":
        SHARE_PATH = os.path.dirname(unicode(sys.executable, sys.getfilesystemencoding()))
        MODULES_PATH = os.path.join(SHARE_PATH, 'modules')
    else:
        SHARE_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), 'share')
        MODULES_PATH = os.path.join(SHARE_PATH, 'cherrytree', 'modules')

__builtin__.SHARE_PATH = SHARE_PATH

sys.path.insert(0, MODULES_PATH)

import main

if len(sys.argv) > 1: OPEN_WITH_FILE = sys.argv[1]
else: OPEN_WITH_FILE = ""

if __name__ == '__main__': main.main(OPEN_WITH_FILE)
