ports:
  - name: cmake
  - name: clang-17
  - name: gettext
  - name: makeicns
  - name: pkgconfig
  - name: python313
  - name: adwaita-icon-theme
  - name: gspell
  - name: gtkmm3
  - name: gtksourceview4
  - name: vte
  - name: libxmlxx2
  - name: libfmt9
  - name: spdlog
  - name: uchardet
  - name: fribidi
  - name: sqlite3
  - name: curl
