.TH CHERRYTREE "1" "June 2020" "cherrytree 0.39.4"
.SH NAME
cherrytree \- a hierarchical note taking application
.SH SYNOPSIS
\fBcherrytree [filepath [\-n nodename] [\-x export_to_html_dir] [\-t export_to_txt_dir] [\-p export_to_pdf_path] [\-w]]\fP
.SH DESCRIPTION
\fBcherrytree\fP is a hierarchical note taking application, featuring rich
text, syntax highlighting, images handling, hyperlinks, import/export with
support for multiple formats, support for multiple languages, and more.
.SH AUTHOR
\fBcherrytree\fP was written by Giuseppe Penone <giuspen@gmail.com> and Evgenii Gurianov <https://github.com/txe>.
.PP
This manual page was written by Vincent Cheng <Vincentc1208@gmail.com>,
for the Debian project (and may be used by others).
