######################################################################
# Automatically generated by qmake (3.0) Fri Jun 2 00:16:43 2017
######################################################################

TEMPLATE = app
TARGET = qscintilla
INCLUDEPATH += .

CONFIG += qscintilla2

# Input
SOURCES += qscintilla.cpp
