.TH CHERRYTREE "1" "August 2013" "cherrytree 0.30.3"
.SH NAME
cherrytree \- a hierarchical note taking application
.SH SYNOPSIS
\fBcherrytree [filepath [\-n nodename]]\fP
.SH DESCRIPTION
\fBcherrytree\fP is a hierarchical note taking application, featuring rich
text, syntax highlighting, images handling, hyperlinks, import/export with
support for multiple formats, support for multiple languages, and more.
.SH AUTHOR
\fBcherrytree\fP was written by Giuseppe Penone <giuspen@gmail.com>.
.PP
This manual page was written by Vincent Cheng <Vincentc1208@gmail.com>,
for the Debian project (and may be used by others).
