name: cherrytree
version: git
summary: Hierarchical note taking application
description: |
  A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single XML or SQLite file. The project home page is giuspen.com/cherrytree.

grade: devel
confinement: strict
base: core18

slots:
  cherrytree:
    interface: dbus
    bus: session
    name: com.giuspen.CherryTreeService

apps:
  cherrytree:
    command: bin/cherrytree
    extensions: [ gnome-3-34 ]
    plugs:
      - home
    desktop: share/applications/cherrytree.desktop

parts:
  cherrytree:
    source: https://github.com/giuspen/cherrytree.git
    source-depth: 1
    plugin: python
    python-version: python2
    build-packages:
      - gettext
      - desktop-file-utils
    stage-packages:
      - python-gtk2
      - python-gtksourceview2
      - p7zip-full
      - python-dbus
      - python-enchant
      - python-chardet
