# SPDX-License-Identifier: GPL-2.0-or-later
name: cherrytree
adopt-info: cherrytree
summary: Hierarchical note taking application
description: |
  A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single XML or SQLite file. The project home page is giuspen.net/cherrytree.

grade: stable
confinement: strict
base: core22
compression: lzo

slots:
  cherrytree-dbus:
    interface: dbus
    bus: session
    name: net.giuspen.cherrytree

environment:
  GTK_USE_PORTAL: '0'

parts:
  cherrytree:
    plugin: cmake
    source-type: git
    source: https://github.com/giuspen/cherrytree.git
    source-commit: 0.99.49
    source-depth: 0
    cmake-parameters:
      - '-DCMAKE_INSTALL_PREFIX='
      - '-DBUILD_TESTING='
      - '-DSNAP_OPT_PRE_CMAKE_INSTALL_PREFIX=/snap/cherrytree/current'
    build-packages:
      - build-essential
      - cmake
      - libcurl4-openssl-dev
      - libfmt-dev
      - libgtksourceviewmm-3.0-dev
      - libgspell-1-dev
      - libpangoft2-1.0-0
      - libsqlite3-dev
      - libspdlog-dev
      - libuchardet-dev
      - libxml++2.6-dev
    stage-packages:
      - libcurl4
      - libfribidi0
      - libgtksourceviewmm-3.0-0v5
      - libspdlog1
      - libuchardet0
      - libxml++2.6-2v5
    prime:
      - -lib/cherrytree/*.a
      - -*canberra*so* # We don't have sound permissions anyway
      - -usr/lib/*/gtk-2.0
    override-build: |
      sed -i 's|^Icon=.*|Icon=${SNAP}/share/icons/hicolor/scalable/apps/cherrytree.svg|' ${CRAFT_PART_SRC}/data/cherrytree.desktop
      craftctl default
    parse-info: [ share/metainfo/net.giuspen.cherrytree.metainfo.xml ]
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/libpangoft2-1.0.so.0

  tinytex:
    source: https://www.giuspen.net/software/TinyTeX-1-v2022.04.04.tar.xz
    source-checksum: sha256/3025930f9c9e989c0cac59826f8ee126d677aec728d20537b9e53e13ace29020
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/TinyTeX
      cp -r * $CRAFT_PART_INSTALL/TinyTeX/

apps:
  cherrytree:
    command: bin/cherrytree
    extensions: [ gnome ]
    plugs:
      - home
      - removable-media
      - network
    slots:
      - cherrytree-dbus
    desktop: share/applications/cherrytree.desktop
    common-id: net.giuspen.cherrytree
