name: MacOS/MacPorts
on: [workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  macos-macports:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up MacPorts
        uses: melusina-org/setup-macports@v1.1.6
        with:
          parameters: .github/parameters/setup-macports.yaml
      - name: CI-Build
        run: |
          pkg-config gtkmm-3.0 --cflags --libs
          ls -la /opt/local/lib | grep fmt
          export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/opt/local/lib/libfmt9/pkgconfig"
          cmake -S . -B build \
                -DBUILD_TESTING='' \
                -DCMAKE_EXE_LINKER_FLAGS="-L/opt/local/lib -L/opt/local/lib/libfmt9"
          cmake --build build
          pip3 install --break-system-packages pyobjc-framework-Cocoa
          cmake --install build
